### ISSUE TITLE
[Suggestion] Add website source label in Sub ID

### ISSUE THREAD

**Issue by TwilightMercy** [Nitzantomer1998/UniversalHebrewSubtitles#3]
Hi,

Thank you again for starting this project!
I've tested multiple movies/tv shows with current Wizdom subs implemented, and everything works well without any issues. 

I have suggestion for future updates, as you plan to add additional subtitles websites to the addon:
To the Sub ID, which is currently the subtitle file name (which is great):

![image](https://github.com/Nitzantomer1998/UniversalHebrewSubtitles/assets/29895680/f2242b4d-faad-4d99-aff9-d1dadc2707e4)

Add the source website, to help differentiate where the subtitle fetched from.
Example:
```[Wizdom] Godzilla x Kong The New Empire 2024 1080p AMZN WEB-DL DDP5 1 1 H 264-FLUX```

Adding example from Kodi subtitles addon:
![image](https://github.com/Nitzantomer1998/UniversalHebrewSubtitles/assets/29895680/39788929-566c-41b3-864b-6d34a6ea1775)

Twilight

**Comment by Nitzantomer1998** [comment]
Great suggestion as I will start to add more sources it will be hard to distinguish between sources.

Unfortunately, the subID will never be good enough. I thought adding the filename would help anyone struggling to find the matching subtitle (even though the first one is always the correct match if it exists). However, I discovered that the name you see when starting a movie or TV series is not the actual name; the real name is sent with the route, meaning the user can't see it—only the server can.

Therefore, I considered three ways to address this:
1. Make the subID consist of the subtitle name followed by a dash and then the torrent filename ([subtitle]-[filename]). However, as you can understand, this is way too long for anyone to bother with.

2. Ignore names as they are not helpful, and just provide a percentage showing how much the subtitle matches the torrent, which is something I am more inclined towards but still not convinced about.

3. Because the first subtitle is always the best match (if its not match then the other wont as well), i though on providing only the most match subtitle and ignore the rest. but people probably like to see a lot of option even if they don't need, so i don't know.

Overall, my main problem is that Stremio (or maybe Torrentio, because I'm only using them) doesn't provide matching names for what the user sees and what the server sees.

Feel free to help me decide or suggest something else, I`m not sure if you are facing the same problem in Kodi

**Comment by TwilightMercy** [comment]
> Great suggestion as I will start to add more sources it will be hard to distinguish between sources.
> 
> 
> 
> (even though the first one is always the correct match if it exists). 

Can you elaborate on that? Do you get the playing video file name from Stremio? Because about a year ago Maor faced this issue:

https://github.com/Stremio/stremio-addon-sdk/issues/221

Which screwed up the process. But I don't know if it's still happens today. 



However, I discovered that the name you see when starting a movie or TV series is not the actual name; the real name is sent with the route, meaning the user can't see it—only the server can.

Can you given examples for the difference between the two names?



> 1. Make the subID consist of the subtitle name followed by a dash and then the torrent filename ([subtitle]-[filename]). However, as you can understand, this is way too long for anyone to bother with.


> 2. Ignore names as they are not helpful, and just provide a percentage showing how much the subtitle matches the torrent, which is something I am more inclined towards but still not convinced about.

I think combining 1+2 will be the best. I think that including filename in the Sub ID will be too long and confusing, and the percentage match is very important for people to see (from long time Israel community experience)


So something like in the picture I sent from DarkSubs addon will be the most helpful:

EDIT



> 3. Because the first subtitle is always the best match (if its not match then the other wont as well), i though on providing only the most match subtitle and ignore the rest. but people probably like to see a lot of option even if they don't need, so i don't know.


Don't go that route from experience:) the more subtitles the better!
A subtitle can fit well to the video even with 20% match for example. 
I suggest having all options to choose without filtering



> Feel free to help me decide or suggest something else, I`m not sure if you are facing the same problem in Kodi

In Kodi the addon can access through Kodi to the playing video file name, and also the video tagline from metadata. (Equal to the source display name in Torrentio results). 
But they are not always the same.

**Comment by Nitzantomer1998** [comment]
> Can you elaborate on that? Do you get the playing video file name from Stremio? About a year ago, Maor faced this issue:

I’m getting the filename from Stremio, the problem you suggest doesn't occur.

> However, I discovered that the name you see when starting a movie or TV series is not the actual name; the real name is sent with the route, meaning the user can’t see it—only the server can.
Can you give examples of the difference between the two names? 

The filename from Stremio doesn't always match the description shown (maybe because I’m using Torrentio). For example, consider "Avatar: The Last Airbender," season 3, episode 1:
- Torrentio shows the torrent as: Avatar:TheLastAirbender-S01 to S03-1080-Bluray-AAC5.1-X264-Rapta Book Three - Fire/Avatar-TheLastAirbender-S03E01-The Awakening.mkv
- Stremio sends it to me as: Avatar - The Last Airbender - S03E01 The Awakening.mkv
- The perfect subtitle is: Avatar.The.Last.Airbender.-,301,-,TheAwekening

As you can see, the Torrentio and Stremio filename representations are different.

**Comment by TwilightMercy** [comment]
> The filename from Stremio doesn't always match the description shown (maybe because I’m using Torrentio). For example, consider "Avatar: The Last Airbender," season 3, episode 1:
> 
> - Torrentio shows the torrent as: Avatar:TheLastAirbender-S01 to S03-1080-Bluray-AAC5.1-X264-Rapta Book Three - Fire/Avatar-TheLastAirbender-S03E01-The Awakening.mkv

First of all, this is not Torrentio specific issue, but a general behavior with torrents. 

The torrent name can have name "X", and the actual video file name can have name "Y", is it very common in cases of season pack torrents - like in the example you gave. 

The torrent have all season and episodes in one combined torrent (called season pack) - hence the name:
Avatar:TheLastAirbender-S01 to S03-1080-Bluray-AAC5.1-X264-Rapta Book Three - Fire

The specific episode video file name is:



> - Stremio sends it to me as: Avatar - The Last Airbender - S03E01 The Awakening.mkv
> 
> - The perfect subtitle is: Avatar.The.Last.Airbender.-,301,-,TheAwekening
> 
> 
> 
> As you can see, the Torrentio and Stremio filename representations are different.
> 
> 
> 
>

**Comment by TwilightMercy** [comment]
Strangely,

All of subtitles represent 0% in all of my testing:


![image](https://github.com/Nitzantomer1998/UniversalHebrewSubtitles/assets/29895680/25da5b4b-3ea5-4cd1-ab1d-4dab0fbc4568)

![image](https://github.com/Nitzantomer1998/UniversalHebrewSubtitles/assets/29895680/5e01416f-fa28-4bfc-be2c-661dc0bcfb02)


![image](https://github.com/Nitzantomer1998/UniversalHebrewSubtitles/assets/29895680/a461dbae-5097-448b-af07-1dac4c3368fb)


![image](https://github.com/Nitzantomer1998/UniversalHebrewSubtitles/assets/29895680/c23846c4-8a1c-46e6-8f90-db212942f84b)

**Comment by Nitzantomer1998** [comment]
It's strange I've tested it multiple times, and it's working properly on several of my accounts and different devices.

I'm aware that Stremio has a built-in cache system, which might be saving old subtitles for a certain amount of time.

If you could, I would appreciate it if you could do the following:
1. Check if the issue still occurs even when it's a movie or series you've never seen before, so there's no possible cache.
2. If it still doesn't work out, please uninstall and then reinstall the addon. After that, check again on a movie or series you've never seen before, and let me know the results so we can verify it.

**Comment by TwilightMercy** [comment]
Indeed strange.
I've first tried to check movies/tv shows I haven't tested before - got same results.

After uninstalling and reinstalling the addon, and checking new series never before opened - still 0%

![image](https://github.com/Nitzantomer1998/UniversalHebrewSubtitles/assets/29895680/5d3e3968-1106-4b98-a9fe-01f1d7d2eb3d)

**Comment by Nitzantomer1998** [comment]
Test that again on a few laptops; it seems to work properly.
So, I'm not sure what advice to give you right now.

I did notice that the instruction from the Stremio developer to update the URL without reinstalling the add-on is sadly false, therefore all the users will have to delete the old one, and install the new one.
So, it's annoying to know that it didn't work, but I didn't have any other options as well.

Perhaps verify that you don't have another installation of a different version of my add-on.

Please take a look at the following images. Note that I only use Wizdom as the provider, but it doesn't affect anything."![image](https://github.com/Nitzantomer1998/UniversalHebrewSubtitles/assets/93198738/f9325815-bd87-4656-ae51-aefeee474238)

![image](https://github.com/Nitzantomer1998/UniversalHebrewSubtitles/assets/93198738/363ca804-1f24-4a79-ad27-2b8fb4758902)

**Comment by TwilightMercy** [comment]
That's really weird.

I logged in to different Stremio account, never installed the addon before, fresh installation of the addon and now I see it:

![image](https://github.com/Nitzantomer1998/UniversalHebrewSubtitles/assets/29895680/ad95db56-014d-4702-b079-cc0a2c46eda2)

![image](https://github.com/Nitzantomer1998/UniversalHebrewSubtitles/assets/29895680/2a2d2049-1e49-4321-92cf-fc4e49090151)

![image](https://github.com/Nitzantomer1998/UniversalHebrewSubtitles/assets/29895680/37cd7aa7-b280-481f-857e-29bd90fb70bd)


Back to my original Stremio account - still 0% (probably weird Stremio caching)

**Comment by TwilightMercy** [comment]
The issue doesn't happen when running free Torrentio version (simple Torrentio install without Debrid account configuration):

![image](https://github.com/Nitzantomer1998/UniversalHebrewSubtitles/assets/29895680/b137170d-c027-4dc8-8049-fe2b630f829c)

![image](https://github.com/Nitzantomer1998/UniversalHebrewSubtitles/assets/29895680/a75f3a2e-0fe0-48f5-923e-41e056fc11f9)

![image](https://github.com/Nitzantomer1998/UniversalHebrewSubtitles/assets/29895680/7772f0ed-f767-4b69-a4d0-fdee8e63f740)

------------------------------------------------------------------------------------------------------------------------------------------------------------


When connecting Torrentio to Real Debrid (premium sources service), I always get 0%:

![image](https://github.com/Nitzantomer1998/UniversalHebrewSubtitles/assets/29895680/f0885fec-baf9-4bf8-9ed2-10fd095f9dd5)


![image](https://github.com/Nitzantomer1998/UniversalHebrewSubtitles/assets/29895680/36b18d92-f108-4280-86cd-d83d03c3f995)

![image](https://github.com/Nitzantomer1998/UniversalHebrewSubtitles/assets/29895680/85d31a20-845b-48e8-a1a2-04ca74a7e840)

------------------------------------------------------------------------------------------------------------------------------------------------------------


I assume this is relevant to the file name extracted from the stream? Usually real debrid sources looks like:

`https://tlv1.download.real-debrid.com/d/<USER_API_KEY>/The.Avengers.2012.720p.BluRay.x264.YIFY.mp4`

When the file name is: The.Avengers.2012.720p.BluRay.x264.YIFY.mp4

Do you have any method to debug it? (Torrentio + RD installation)

**Comment by Nitzantomer1998** [comment]
It's truly intriguing that you've discovered that detail, especially considering my inability to verify it with the paid version.

However, the implications of this process remain somewhat murky. Stremio add-ons function within a strict framework, where each, whether free or paid, must adhere precisely to Stremio's standards.

Add-ons from the same service should ideally produce consistent results (assuming proper functionality). Whether free or paid, they all generate a JavaScript object meticulously structured to meet Stremio's specifications. For instance, subtitles must contain specific properties for seamless integration (you can refer to the required properties outlined here: [Stremio Subtitle Object](https://github.com/Stremio/stremio-addons/blob/master//docs/api/subtitles/subtitles.object.md)). Drawing a parallel to your Python development, this structure resembles a dictionary, scrutinized by Stremio upon return.

Each add-on interacts exclusively with Stremio through designated routes/URLs, effectively isolating them from external influences, unless they fail to furnish essential details.

My add-on relies entirely on information provided by Stremio when users interact with content, extracted via:
> src/routes/stremioRoute.js:
1. router.get("/subtitles/:contentType/:compoundID/:extraArgs.json", corsMiddleware, wrapTryCatch(stremioController.getSubtitlesList));
2. router.get("/:userConfig/subtitles/:contentType/:compoundID/:extraArgs.json", corsMiddleware, wrapTryCatch(stremioController.getSubtitlesList));

As evident, I extract the necessary data from Stremio's route, under close supervision by the platform itself. However, it's worth noting that missing information may occur, particularly if paid torrentio **fails to send the filename to Stremio** (likely a bug). This could pose challenges with string comparison, potentially resulting in a 0% match being flagged.

**Comment by TwilightMercy** [comment]
Looking at:
https://github.com/Nitzantomer1998/UniversalHebrewSubtitles/blob/main/src/utils/filenameExtractor.js

I see that you extract `filename=XXXXXXXXXXX` from Stremio extra arguments.

When using free Torrentio version - Do you get in filename the exact name you need, If I understand correctly?

Example:
`filename=The.Avengers.2012.720p.BluRay.x264.YIFY.mp4`

If that's the case, and through Torrentio + RD, you get the direct stream URL (since it's not a torrent stream, it's direct https streaming), example:
`filename=https://tlv1.download.real-debrid.com/d/<USER_API_KEY>/The.Avengers.2012.720p.BluRay.x264.YIFY.mp4`

Then it's solvable in `extractFilename` function, example to DarkSubs addon implementation:

```python
def get_playing_filename_and_remove_extension_if_exists():

    # Get the full path of the currently playing video and unquote it to handle any URL encoding
    filename = xbmc.Player().getPlayingFile()
    
    # Split the path to remove any query parameters
    filename = filename.split("?")[0]
    
    # Extract the basename of the file from the path
    filenameValue = os.path.basename(filename)
    
    # Extract the basename of the file from the path
    file_name_without_extension, file_extension = os.path.splitext(filenameValue)
    
    # Define a list of common video file extensions
    video_file_extensions = ['mkv', 'mp4', 'm4p', 'avi', 'mov', 'mpeg', 'mpg', 'flv', 'wmv', 'm4v', 'webm', '3gp', 'ogg', 'ogv', 'rmvb', 'divx', 'vob', 'dat', 'mts', 'm2ts', 'ts', 'yuv']
    
    # If the extension is in the list of video extensions, remove it
    if file_extension.lstrip('.') in video_file_extensions:
        filenameValue = file_name_without_extension
        
    return filenameValue
``` 

JS version (converted by ChatGPT xd):

```javascript
const extractFilename = (extraArgs) => {
    const filename = extraArgs.split('&').find(key => key.startsWith('filename='));
    const filenameValue = filename ? filename.split('=')[1] : "";

    // Remove query parameters from filenameValue
    filenameValue = filenameValue.split('?')[0];

    // Extract filename from path
    filenameValue = filenameValue.split('/').pop();

    // Remove video file extensions from filename
    const videoFileExtensions = /\.(mkv|mp4|m4p|avi|mov|mpeg|mpg|flv|wmv|m4v|webm|3gp|ogg|ogv|rmvb|divx|vob|dat|mts|m2ts|ts|yuv)$/i;
    filenameValue = filenameValue.replace(videoFileExtensions, '');

    return filenameValue
};
```


If that's the case and you want help in debugging the filename param you get through paid Torrentio, I can send you my Real Debrid API Key in private email, so you can configure it through https://torrentio.strem.fun/.
And renew it when you're done testing, no problem for me.

**Comment by TwilightMercy** [comment]
No problem, I'm available tonight for quick responses 👍🏻

**Comment by TwilightMercy** [comment]
How can I access it?

**Comment by TwilightMercy** [comment]
Sent.

**Comment by TwilightMercy** [comment]
> The filename from Stremio doesn't always match the description shown (maybe because I’m using Torrentio). For example, consider "Avatar: The Last Airbender," season 3, episode 1:
> 
> - Torrentio shows the torrent as: Avatar:TheLastAirbender-S01 to S03-1080-Bluray-AAC5.1-X264-Rapta Book Three - Fire/Avatar-TheLastAirbender-S03E01-The Awakening.mkv
> 
> - Stremio sends it to me as: Avatar - The Last Airbender - S03E01 The Awakening.mkv

As plan B for Torrentio + Real Debrid for comparing the strings, if not through filename, do you have access to the description for the

**Comment by Nitzantomer1998** [comment]
> As plan B for Torrentio + Real Debrid for comparing the strings, if not through filename, do you have access to the description for the string similarity check?

That's the problem—there's no way to access anything beyond what is provided in the route.

I also explored the option of finding a service that allows sending parameters like the videoHash to retrieve information, but such a service does not exist.

As for Real Debrid, unfortunately, we currently have no solution. Here are the steps I've taken so far:
- Opened an issue for the Stremio addon
- Opened an issue for Torrentio
- Opened a Reddit thread

So far, there have been no answers (not helpful ones). when there will be a solution i will solve it ASAP

**Comment by TwilightMercy** [comment]
https://github.com/TheBeastLT/torrentio-scraper/commit/0105173c6a7560d765212e58c0f536fbdc148e5a
